# Generated by Django 5.2 on 2025-04-15 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=200)),
                ('lab_type', models.CharField(choices=[('HOSPITAL', 'Hospital Laboratory'), ('PRIVATE', 'Private Laboratory'), ('UNIVERSITY', 'University Laboratory'), ('OTHER', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('referral_type', models.CharField(choices=[('INTERNAL', 'Internal Only'), ('EXTERNAL', 'Internal and External')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='lab_uploads/')),
                ('processed', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_code', models.CharField(max_length=20)),
                ('parameter_name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=50)),
                ('preanalytical', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('analytical', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('expertise', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('postanalytical', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('administrative', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('invasiveness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('time_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evaluations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_code', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.laboratory')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.laboratoryupload')),
            ],
            options={
                'unique_together': {('laboratory', 'loinc_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BenchmarkingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('percentile_rank', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.laboratory')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.parameterevaluation')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llpc.parametervolume')),
            ],
        ),
    ]
